### PR TITLE
docs: update demo gif with new design

### PR DESCRIPTION
**Pull request by paouvrard**
Updated gif in the readme:
https://github.com/near/rainbow-bridge-frontend/tree/update_gif

### CODE REVIEW

**Review by djsatok — APPROVED** [review]
LGTM

**Comment by mfornet** [comment]
The gif content looks good to me, however, not sure if it is my browser or the gif itself, it doesn't run smooth.

**Comment by paouvrard** [comment]
The gif is made from screenshots..

**Comment by chadoh** [comment]
On a Mac, you can use Kap to make nice gifs from screen recordings

**Pull request merged**
