### PR TITLE
refactor: rm unused libs from package.json

### PR DESCRIPTION
**Pull request by chadoh**
cleanup enabled by 55ee5c4a6bce33ea7ed55972e45e6c1113f0de5a

### CODE REVIEW

**Comment by paouvrard** [comment]
thanks !
`web3` can be removed after #120 is merged
but `decimal.js` will still be needed in erc20-form.html

**Comment by chadoh** [comment]
@paouvrard ah, thanks! I think it seems right now.

**Comment by djsatok** [comment]
@paouvrard are you OK with the change?

**Pull request merged**
